export const teamList = [
  {
    name: "Aksh Bansal",
    team: "dev",
    profileImg: "aksh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/aksh-bansal-0a1073200/",
    codeforcesProfileUrl: "https://codeforces.com/profile/SaberXpro",
    githubProfileUrl: "https://www.github.com/Aksh-Bansal-dev",
    email: "20bcs021@iiitdmj.ac.in",
  },
  {
    name: "Akshat Nema",
    team: "dev",
    profileImg: "akshat.png",
    linkedInProfileUrl: "https://linkedin.com/in/akshat-nema",
    githubProfileUrl: "https://github.com/akshatnema",
    email: "20bcs022@iiitdmj.ac.in",
  },
  {
    name: "Manav Desai",
    team: "dev",
    profileImg: "manav.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/manavdesai27",
    githubProfileUrl: "https://github.com/manavdesai27",
    email: "manav27202@gmail.com",
  },
  {
    name: "Tushar Jain",
    team: "dev",
    profileImg: "tushar.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/jain0735",
    linkedInProfileUrl: "https://www.linkedin.com/in/tushar-jain4/",
    githubProfileUrl: "https://github.com/Tusharjain123",
    email: "jain0735@gmail.com",
  },
  {
    name: "Shashwat Gupta",
    team: "Coordinator",
    profileImg: "shashwat.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/masterchief164",
    githubProfileUrl: "https://www.github.com/masterchief164",
    email: "shaswat2001.sg@gmail.com",
  },
  {
    name: "Priyansh Mehta",
    team: "Co Coordinator",
    profileImg: "priyansh.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/priyansh61/",
    githubProfileUrl: "https://github.com/Priyansh61",
    email: "21bec080@iiitdmj.ac.in",
  },
  {
    name: "Samyak Bhargava",
    team: "dev",
    profileImg: "samyak.jpeg",
    codeforcesProfileUrl: "https://codeforces.com/profile/Sammybh6",
    linkedInProfileUrl: "https://www.linkedin.com/in/sammybh6/",
    githubProfileUrl: "https://github.com/sammybh6",
    email: "samyakbhargava9@gmail.com",
  },
  {
    name: "Tushir Sahu",
    team: "dev",
    profileImg: "tushir.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/tushir-sahu-b95549205/",
    githubProfileUrl: "https://github.com/TushirSahu",
    email: "tushirsahu30@gmail.com",
  },
  {
    name: "Himanshu Aggarwal",
    team: "cp",
    profileImg: "himanshu.jpeg",
    codeforcesProfileUrl: "https://codeforces.com/profile/NightSky",
    linkedInProfileUrl: "https://www.linkedin.com/in/himanshu0923",
    email: "20bcs102@iiitdmj.ac.in",
  },
  {
    name: "Paras Gami",
    team: "cp",
    profileImg: "paras.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/paras__g3",
    linkedInProfileUrl: "https://www.linkedin.com/in/paras-gami-54719b1b8/",
    githubProfileUrl: "https://github.com/theparasgami",
    email: "20BCS151@iiitdmj.ac.in",
  },
  {
    name: "Armin Patel",
    team: "cp",
    profileImg: "avatar.png",
    codeforcesProfileUrl: "https://codeforces.com/profile/0xarmin",
    linkedInProfileUrl: "https://www.linkedin.com/in/arminpatel",
    githubProfileUrl: "https://github.com/arminpatel",
    email: "21bcs031@iiitdmj.ac.in",
  },
  {
    name: "Prajwal Rayal",
    team: "cp",
    profileImg: "avatar.png",
    codeforcesProfileUrl: "https://codeforces.com/profile/Prajwalrayal",
    linkedInProfileUrl: "https://www.linkedin.com/in/prajwal-rayal-30b323222",
    email: "21bec077@iiitdmj.ac.in",
  },
  {
    name: "Varun Singh",
    team: "dev",
    profileImg: "varun.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/varun-singh-018242224",
    githubProfileUrl: "https://github.com/varun7singh",
    email: "varun7singh10@gmail.com",
  },
  {
    name: "Prajjwal Kapoor",
    team: "dev",
    profileImg: "prajjwal.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/prajjwal-kapoor/",
    githubProfileUrl: "https://github.com/prajjwalkapoor",
    email: "prajjwal.kapoor.mail@gmail.com",
  },
  {
    name: "Aishwarya Saxena",
    team: "cp",
    profileImg: "aishwarya.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/ASH0705",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/aishwarya-saxena-05713618b/",
    githubProfileUrl: "https://github.com/aish0749",
    email: "aishwarya0749@gmail.com",
  },
  {
    name: "Deepanshu Singh",
    team: "cp",
    profileImg: "avatar.png",
    codeforcesProfileUrl: "https://codeforces.com/profile/sdeepanshu17 ",
    linkedInProfileUrl: "https://www.linkedin.com/in/sdeepanshu17",
    email: "21bcs073@iiitdmj.ac.in",
  },
  {
    name: "Divyansh Tripathi",
    team: "cp",
    profileImg: "divyansh.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/gtheoden42",
    linkedInProfileUrl: "https://www.linkedin.com/in/tdivyansh058",
    githubProfileUrl: "https://github.com/theoden42",
    email: "divy000trip@gmail.com",
  },
  {
    name: "Siddhant Raj",
    team: "cp",
    profileImg: "siddhant.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/Fury_04",
    linkedInProfileUrl: "https://in.linkedin.com/in/siddhant-raj-93a2101b1",
    githubProfileUrl: "https://github.com/Siddr04",
    email: "21bcs199@iiitdmj.ac.in",
  },
  {
    name: "Prakash Dwivedi",
    team: "cp",
    profileImg: "prakash.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/PraKash5",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/prakash-dwivedi-81664b229/",
    email: "dprakash2103@gmail.com",
  },
  {
    name: "Prabal Pratap Singh",
    team: "cp",
    profileImg: "prabal.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/prabalpsingh7115",
    linkedInProfileUrl: "https://www.linkedin.com/in/prabapsingh7115/",
    githubProfileUrl: "https://github.com/Prabalpsingh7115",
    email: "21bec076@iiitdmj.ac.in",
  },
  {
    name: "Shreya Singh",
    team: "cp",
    profileImg: "avatar.png",
    linkedInProfileUrl: "https://www.linkedin.com/in/shreya-singh-2b61b8227/",
    githubProfileUrl: "https://github.com/Shreya0511",
    email: "singh.shreya0511@gmail.com",
  },
  {
    name: "Pranjal jha",
    team: "dev",
    profileImg: "pranjal.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/pranjal-jha-85880a229/",
    githubProfileUrl: "https://github.com/PraneGIT",
    email: "pranjaljha00@gmail.com",
  },
  {
    name: "Bhavik Agarwal",
    team: "cp",
    profileImg: "bhavik.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/bhavik_2001",
    linkedInProfileUrl: "https://www.linkedin.com/in/bhavikagarwal2001/",
    githubProfileUrl: "https://github.com/Bhavik-ag",
    email: "21bcs056@iiitdmj.ac.in",
  },
  {
    name: "Yash Rastogi",
    team: "cp",
    profileImg: "yash.jpg",
    codeforcesProfileUrl:
      "https://codeforces.com/profile/yashrastogi543?mobile=false",
    linkedInProfileUrl: "https://www.linkedin.com/in/yash-rastogi-51ab05229/",
    email: "yashrastogi543@gmail.com",
  },
  {
    name: "Nitya Tiwari",
    team: "cp",
    profileImg: "nitya.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/Azalea05",
    linkedInProfileUrl: "https://www.linkedin.com/in/nitya-tiwari-960797229/",
    githubProfileUrl: "https://github.com/nityatiwari002",
    email: "21bcs150@iiitdmj.ac.in",
  },
  {
    name: "Priyanshu Agarwal",
    team: "dev",
    profileImg: "priyanshu.jpg",
    linkedInProfileUrl:
      "http://www.linkedin.com/in/priyanshu-agarwal-484151220/",
    githubProfileUrl: "https://github.com/AgPriyanshu18",
    email: "agpriyanshu18@gmail.com",
  },
  {
    name: "Rishabh Gupta",
    team: "dev",
    profileImg: "rishabh.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/rishabh-g-014020139/",
    codeforcesProfileUrl: "https://codeforces.com/profile/_callmegupta",
    githubProfileUrl: "https://github.com/IamRishabhGupta",
    email: "rishabh9aug@gmail.com",
  },
  {
    name: "Aman Srivastava",
    team: "cp",
    profileImg: "aman.jpeg",
    codeforcesProfileUrl: "https://codeforces.com/profile/aman_sriv",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/aman-srivastava-16726822a/",
    githubProfileUrl: "https://github.com/AmanSrivastavaERC",
    email: "21bec014@iiitdmj.ac.in",
  },
];
