export const teamList_20 = [
  {
    name: "Akshat Nema",
    team: "dev",
    profileImg: "akshat.png",
    linkedInProfileUrl: "https://linkedin.com/in/akshat-nema",
    githubProfileUrl: "https://github.com/akshatnema",
    email: "20bcs022@iiitdmj.ac.in",
  },
  {
    name: "Manav Desai",
    team: "dev",
    profileImg: "manav.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/manavdesai27",
    githubProfileUrl: "https://github.com/manavdesai27",
    email: "manav27202@gmail.com",
  },
  {
    name: "Aksh Bansal",
    team: "dev",
    profileImg: "aksh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/aksh-bansal-0a1073200/",
    codeforcesProfileUrl: "https://codeforces.com/profile/SaberXpro",
    githubProfileUrl: "https://www.github.com/Aksh-Bansal-dev",
    email: "20bcs021@iiitdmj.ac.in",
  },
  {
    name: "Himanshu Aggarwal",
    team: "cp",
    profileImg: "himanshu.jpeg",
    codeforcesProfileUrl: "https://codeforces.com/profile/NightSky",
    linkedInProfileUrl: "https://www.linkedin.com/in/himanshu0923",
    email: "20bcs102@iiitdmj.ac.in",
  },
  {
    name: "Paras Gami",
    team: "cp",
    profileImg: "paras.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/paras__g3",
    linkedInProfileUrl: "https://www.linkedin.com/in/paras-gami-54719b1b8/",
    githubProfileUrl: "https://github.com/theparasgami",
    email: "20BCS151@iiitdmj.ac.in",
  },
];

export const teamList_21 = [
  {
    name: "Tushar Jain",
    team: "dev",
    profileImg: "tushar.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/jain0735",
    linkedInProfileUrl: "https://www.linkedin.com/in/tushar-jain4/",
    githubProfileUrl: "https://github.com/Tusharjain123",
    email: "jain0735@gmail.com",
  },
  {
    name: "Shashwat Gupta",
    team: "Coordinator",
    profileImg: "shashwat.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/masterchief164",
    githubProfileUrl: "https://www.github.com/masterchief164",
    email: "shaswat2001.sg@gmail.com",
  },
  {
    name: "Priyansh Mehta",
    team: "Co Coordinator",
    profileImg: "priyansh.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/priyansh61/",
    githubProfileUrl: "https://github.com/Priyansh61",
    email: "21bec080@iiitdmj.ac.in",
  },
  {
    name: "Samyak Bhargava",
    team: "dev",
    profileImg: "samyak.jpeg",
    codeforcesProfileUrl: "https://codeforces.com/profile/Sammybh6",
    linkedInProfileUrl: "https://www.linkedin.com/in/sammybh6/",
    githubProfileUrl: "https://github.com/sammybh6",
    email: "samyakbhargava9@gmail.com",
  },
  {
    name: "Tushir Sahu",
    team: "dev",
    profileImg: "tushir.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/tushir-sahu-b95549205/",
    githubProfileUrl: "https://github.com/TushirSahu",
    email: "tushirsahu30@gmail.com",
  },
  {
    name: "Armin Patel",
    team: "cp",
    profileImg: "avatar.png",
    codeforcesProfileUrl: "https://codeforces.com/profile/0xarmin",
    linkedInProfileUrl: "https://www.linkedin.com/in/arminpatel",
    githubProfileUrl: "https://github.com/arminpatel",
    email: "21bcs031@iiitdmj.ac.in",
  },
  {
    name: "Prajwal Rayal",
    team: "cp",
    profileImg: "avatar.png",
    codeforcesProfileUrl: "https://codeforces.com/profile/Prajwalrayal",
    linkedInProfileUrl: "https://www.linkedin.com/in/prajwal-rayal-30b323222",
    email: "21bec077@iiitdmj.ac.in",
  },
  {
    name: "Varun Singh",
    team: "dev",
    profileImg: "varun.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/varun-singh-018242224",
    githubProfileUrl: "https://github.com/varun7singh",
    email: "varun7singh10@gmail.com",
  },
  {
    name: "Prajjwal Kapoor",
    team: "dev",
    profileImg: "prajjwal.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/prajjwal-kapoor/",
    githubProfileUrl: "https://github.com/prajjwalkapoor",
    email: "prajjwal.kapoor.mail@gmail.com",
  },
  {
    name: "Aishwarya Saxena",
    team: "cp",
    profileImg: "aishwarya.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/ASH0705",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/aishwarya-saxena-05713618b/",
    githubProfileUrl: "https://github.com/aish0749",
    email: "aishwarya0749@gmail.com",
  },
  {
    name: "Deepanshu Singh",
    team: "cp",
    profileImg: "avatar.png",
    codeforcesProfileUrl: "https://codeforces.com/profile/sdeepanshu17 ",
    linkedInProfileUrl: "https://www.linkedin.com/in/sdeepanshu17",
    email: "21bcs073@iiitdmj.ac.in",
  },
  {
    name: "Divyansh Tripathi",
    team: "cp",
    profileImg: "divyansh.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/gtheoden42",
    linkedInProfileUrl: "https://www.linkedin.com/in/tdivyansh058",
    githubProfileUrl: "https://github.com/theoden42",
    email: "divy000trip@gmail.com",
  },
  {
    name: "Siddhant Raj",
    team: "cp",
    profileImg: "siddhant.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/Fury_04",
    linkedInProfileUrl: "https://in.linkedin.com/in/siddhant-raj-93a2101b1",
    githubProfileUrl: "https://github.com/Siddr04",
    email: "21bcs199@iiitdmj.ac.in",
  },
  {
    name: "Prakash Dwivedi",
    team: "cp",
    profileImg: "prakash.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/PraKash5",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/prakash-dwivedi-81664b229/",
    email: "dprakash2103@gmail.com",
  },
  {
    name: "Prabal Pratap Singh",
    team: "cp",
    profileImg: "prabal.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/prabalpsingh7115",
    linkedInProfileUrl: "https://www.linkedin.com/in/prabapsingh7115/",
    githubProfileUrl: "https://github.com/Prabalpsingh7115",
    email: "21bec076@iiitdmj.ac.in",
  },
  {
    name: "Shreya Singh",
    team: "cp",
    profileImg: "avatar.png",
    linkedInProfileUrl: "https://www.linkedin.com/in/shreya-singh-2b61b8227/",
    githubProfileUrl: "https://github.com/Shreya0511",
    email: "singh.shreya0511@gmail.com",
  },
  {
    name: "Pranjal jha",
    team: "dev",
    profileImg: "pranjal.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/pranjal-jha-85880a229/",
    githubProfileUrl: "https://github.com/PraneGIT",
    email: "pranjaljha00@gmail.com",
  },
  {
    name: "Bhavik Agarwal",
    team: "cp",
    profileImg: "bhavik.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/bhavik_2001",
    linkedInProfileUrl: "https://www.linkedin.com/in/bhavikagarwal2001/",
    githubProfileUrl: "https://github.com/Bhavik-ag",
    email: "21bcs056@iiitdmj.ac.in",
  },
  {
    name: "Yash Rastogi",
    team: "cp",
    profileImg: "yash.jpg",
    codeforcesProfileUrl:
      "https://codeforces.com/profile/yashrastogi543?mobile=false",
    linkedInProfileUrl: "https://www.linkedin.com/in/yash-rastogi-51ab05229/",
    email: "yashrastogi543@gmail.com",
  },
  {
    name: "Nitya Tiwari",
    team: "cp",
    profileImg: "nitya.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/Azalea05",
    linkedInProfileUrl: "https://www.linkedin.com/in/nitya-tiwari-960797229/",
    githubProfileUrl: "https://github.com/nityatiwari002",
    email: "21bcs150@iiitdmj.ac.in",
  },
  {
    name: "Priyanshu Agarwal",
    team: "dev",
    profileImg: "priyanshu.jpg",
    linkedInProfileUrl:
      "http://www.linkedin.com/in/priyanshu-agarwal-484151220/",
    githubProfileUrl: "https://github.com/AgPriyanshu18",
    email: "agpriyanshu18@gmail.com",
  },
  {
    name: "Rishabh Gupta",
    team: "dev",
    profileImg: "rishabh.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/rishabh-g-014020139/",
    codeforcesProfileUrl: "https://codeforces.com/profile/_callmegupta",
    githubProfileUrl: "https://github.com/IamRishabhGupta",
    email: "rishabh9aug@gmail.com",
  },
  {
    name: "Aman Srivastava",
    team: "cp",
    profileImg: "aman.jpeg",
    codeforcesProfileUrl: "https://codeforces.com/profile/aman_sriv",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/aman-srivastava-16726822a/",
    githubProfileUrl: "https://github.com/AmanSrivastavaERC",
    email: "21bec014@iiitdmj.ac.in",
  },
];

export const teamList_22 = [
  {
    name: "Pratik Solanki",
    team: "dev",
    profileImg: "pratik.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/pratik-solanki-a140a7257/",
    githubProfileUrl: "https://github.com/Pratik2026",
    email: "pratiksolanki2026@gmail.com",
  },
  {
    name: "Vedant Jain",
    team: "dev",
    profileImg: "vedant.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/vedant-jain-4733a4250/",
    githubProfileUrl: "https://github.com/jainvedant392",
    email: "jainvedant392@gmail.com",
  },
  {
    name: "Eshaan Modi",
    team: "dev",
    profileImg: "eshaan.jpg",
    linkedInProfileUrl: "www.linkedin.com/in/eshaan-modi-a9a602253",
    githubProfileUrl: "https://github.com/NightFury742",
    email: "eshaan122@gmail.com",
  },
  {
    name: "Shraman Paul",
    team: "dev",
    profileImg: "ShramanPaul.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/shraman-paul-15ba04257/",
    githubProfileUrl: "https://github.com/shramanpaul",
    email: "22bcs229@iiitdmj.ac.in",
  },
  {
    name: "Neyati",
    team: "dev",
    profileImg: "neyati.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/neyati-iiit/",
    githubProfileUrl: "https://github.com/Doraemon012",
    email: "neyati28@gmail.com",
  },
  {
    name: "Aditya Ghai",
    team: "dev",
    profileImg: "Aditya.jpg",
    linkedInProfileUrl: " www.linkedin.com/in/aditya-ghai-71326124a",
    githubProfileUrl: "https://github.com/adityaghai07 ",
    email: "22bcs011@iiitdmj.ac.in ",
  },
  {
    name: "Shreyans Kataria",
    team: "dev",
    profileImg: "shreyans.jpg",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/shreyans-katariya-501489260/ ",
    githubProfileUrl: "https://github.com/Shreyans2004 ",
    email: "22bcs231@iiitdmj.ac.in ",
  },
  {
    name: "Joyee Biswas",
    team: "dev",
    profileImg: "joyee.jpg",
    linkedInProfileUrl: " https://www.linkedin.com/in/joyee-biswas-807b53258",
    githubProfileUrl: "https://github.com/Joyee2004 ",
    email: "22bcs116@iiitdmj.ac.in ",
  },
  {
    name: "Dhruv Parmar",
    team: "dev",
    profileImg: "dhruv.jpg",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/dhruv-parmar-61b31226b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubProfileUrl: "https://github.com/REC-1104",
    email: "dhruvparmar110404@gmail.com",
  },
  {
    name: "Shivansh Fulper",
    team: "dev",
    profileImg: "Shivansh.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/shivansh-fulper-463968223",
    githubProfileUrl: " https://github.com/Pin4sf ",
    email: " 22bsm054@iiitdmj.ac.in ",
  },
  {
    name: "Agrim Gupta",
    team: "dev",
    profileImg: "agrim.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/agrim-gupta-203570265",
    githubProfileUrl: " https://github.com/Agrim2112",
    email: "22bcs016@iiitdmj.ac.in",
  },
  {
    name: "Aditya kumar Gupta",
    team: "dev",
    profileImg: "Aditya_Gupta.jpg",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/aditya-kumar-gupta-b52a9426b",
    githubProfileUrl: "https://github.com/Adi8712",
    email: "22bcs012@iiitdmj.ac.in",
  },
  {
    name: "Akshay Bhel",
    team: "dev",
    profileImg: "akshay.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/akshay-behl-450661258/",
    githubProfileUrl: "https://github.com/Captain-T2004",
    email: "akshaybehl231@gmail.com",
  },
  {
    name: "Prince Bhujethia",
    team: "dev",
    profileImg: "prince.jpg",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/prince-bujethia-60850a1a0/",
    githubProfileUrl: "https://github.com/PrinceBujethia",
    email: "22bc200@iiitdmj.ac.in",
  },
  {
    name: "Divyansh Bisht",
    team: "cp",
    profileImg: "divyansh_bisht.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/DCODER_13",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/divyansh-bisht-1294b1264/ ",
    githubProfileUrl: "https://github.com/dcoder13",
    email: "22bcs085@iiitdmj.ac.in",
  },
  {
    name: "Himanshu Kamble",
    team: "cp",
    profileImg: "Himanshu_kamble.jpeg",
    codeforcesProfileUrl: "https://codeforces.com/profile/d0tniiko",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/himanshu-kamble-22ba3624b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubProfileUrl: "https://github.com/dotniiko",
    email: "22bcs108@iiitdmj.ac.in",
  },
  {
    name: "Rajavamshi",
    team: "cp",
    profileImg: "Rajavamshi.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/vamshi_75",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/vallakati-rajavamshinath-208801254/",
    githubProfileUrl: "https://github.com/rVnCoder",
    email: "22bcs264@iiitdmj.ac.in",
  },
  {
    name: "Uttara Kamat",
    team: "cp",
    profileImg: "uttara.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/idlidosa_1206",
    linkedInProfileUrl: "https://www.linkedin.com/in/uttara-kamat/",
    githubProfileUrl: "https://github.com/idlidosa1206",
    email: "22bcs126@iiitdmj.ac.in ",
  },
  {
    name: "Rishi Godre",
    team: "cp",
    profileImg: "Rishi.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/rishigodre14",
    linkedInProfileUrl: "www.linkedin.com/in/rishi-godre-31323624b",
    email: "22bec100@iiitdmj.ac.in",
  },
  {
    name: "Akash Kumar Shah",
    team: "cp",
    profileImg: "AkashSah.png",
    codeforcesProfileUrl: "https://codeforces.com/profile/akashsah2003",
    linkedInProfileUrl: "https://www.linkedin.com/in/akashsah2003/",
    githubProfileUrl: "https://github.com/Akashsah2003",
    email: "akashsah2003@gmail.com",
  },
  {
    name: "Keyur Joshi",
    team: "cp",
    profileImg: "keyur.jpg",
    codeforcesProfileUrl: "https://codeforces.com/profile/keyur03",
    linkedInProfileUrl: "https://www.linkedin.com/in/keyur-doshi-990485250/",
    githubProfileUrl: "https://github.com/keyur-doshi",
    email: "22bcs137@iiitdmj.ac.in",
  },
  {
    name: "Aishwarya Ghatole",
    team: "design",
    profileImg: "Aishwarya.jpeg",
    linkedInProfileUrl:
      "https://www.linkedin.com/in/aishwarya-ghatole-506745231",
    email: "aishwaryaghatole2721@gmail.com",
  },
  {
    name: "Aman Raj",
    team: "design",
    profileImg: "aman_raj.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/aman-r-1676751b6",
    email: "22bcs027@gmail.com",
  },
];
