export const teamlist = [
  {
    name: "Aksh Bansal",
    team: "dev",
    profileImg: "aksh.jpg",
    linkedIn: "https://www.linkedin.com/in/aksh-bansal-0a1073200/",
    github: "https://www.github.com/Aksh-Bansal-dev",
    email: "20bcs021@iiitdmj.ac.in",
  },
  {
    name: "Priyansh Garg",
    team: "coordinator",
    profileImg: "priyansh.jpeg",
    linkedIn: "https://www.linkedin.com/in/priyansh3133/",
    github: "https://www.github.com/garg3133",
    email: "2018196@iiitdmj.ac.in",
  },
  {
    name: "Taara Sinh Aatrey",
    team: "coco",
    profileImg: "taara.jpeg",
    linkedIn: "https://www.linkedin.com/in/aatrey07/",
    github: "https://www.github.com/Taara-Sinh-Aatrey",
    email: "2019348@iiitdmj.ac.in",
  },
  {
    name: "Nandani Patel",
    team: "cp",
    profileImg: "nandani.jpeg",
    linkedIn: "https://www.linkedin.com/in/nandani-patel-1bb1a11ba",
    github: "https://www.github.com/nandani-patel",
    email: "20bcs140@iiitdmj.ac.in",
  },
  {
    name: "Bhawna Khatri",
    team: "dev",
    profileImg: "bhawna.jpg",
    linkedIn: "https://www.linkedin.com/in/bhawna-khatri-41aa11184",
    github: "https://www.github.com/Bhawna147",
    email: "Khatribhawna77@gmail.com",
  },
  {
    name: "Himanshu Aggarwal",
    team: "cp",
    profileImg: "avatar.png",
    linkedIn: "https://www.linkedin.com/in/himanshu0923",
    github: "https://www.github.com/HimanShu0923",
    email: "20bcs102@iiitdmj.ac.in",
  },
  {
    name: "Manan Jethwani",
    team: "dev",
    profileImg: "manan.jpeg",
    linkedIn: "https://www.linkedin.com/in/manan-jethwani/",
    github: "https://www.github.com/MananJethwani",
    email: "2019282@iiitdmj.ac.in",
  },
];
