export const alumniList = [
  {
    name: "Sagar Ranglani",
    description: "Coordinator (2007-08)",
    profileImg: "Sagar.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/sagarranglani/",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Arpit Garg",
    description: "Coordinator (2015-16)",
    profileImg: "Arpit.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/arpitgarg96/",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Saurabh Joshi",
    description: "Coordinator (2016-17)",
    profileImg: "Saurabh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/apptica",
    githubProfileUrl: "https://github.com/Apptica",
    email: "",
  },
  {
    name: "Adarsh Singh",
    description: "Co-Coordinator (2016-17)",
    profileImg: "Adarsh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/adarsh-singh-036985126",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Anuraag Singh",
    description: "Coordinator (2017-18)",
    description2: "Co-Coordinator (2016-17)",
    profileImg: "Anuraag.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/anuraag-singh-231661113",
    githubProfileUrl: "https://www.github.com/anuraagheisenberg",
    email: "dbaanurag@gmail.com",
  },
  {
    name: "Nakul Arya",
    description: "Coordinator (2017-18)",
    profileImg: "Nakul.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/aryanakul/",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Arpan Tarkas",
    description: "Coordinator (2018-19)",
    description2: "Co-Coordinator (2017-18)",
    profileImg: "Arpan.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/arpantarkas",
    githubProfileUrl: "https://github.com/arpantarkas",
    email: "",
  },
  {
    name: "Anuj Singh",
    description: "Co-Coordinator (2018-19)",
    profileImg: "avatar.png",
    linkedInProfileUrl: "https://www.linkedin.com/in/chauhan176",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Shivansh Dhiman",
    description: "Co-Coordinator (2018-19)",
    profileImg: "Shivansh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/shivansh-dhiman",
    githubProfileUrl: "https://github.com/shivansh1010",
    email: "",
  },
  {
    name: "Anshuman Sharma",
    description: "Co-Coordinator (2018-19)",
    profileImg: "Anshuman.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/-anshuman-sharma-",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Ajwad Shaikh",
    description: "Coordinator (2019-20)",
    profileImg: "Ajwad.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/ajwad-shaikh",
    githubProfileUrl: "https://www.github.com/ajwad-shaikh",
    email: "",
  },
  {
    name: "Pranav Khiste",
    description: "Co-Coordinator (2019-20)",
    profileImg: "Pranav.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/pranav-khiste-2a38a116a",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Shrey Goel",
    description: "Co-Coordinator (2019-20)",
    profileImg: "Shrey.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/shrey-goel-21492194",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Priyansh Garg",
    description: "Coordinator (2020-22)",
    profileImg: "priyansh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/priyansh3133/",
    githubProfileUrl: "https://github.com/garg3133",
    email: "",
  },
  {
    name: "Manan Jethwani",
    description: "Co-Coordinator (2020-21)",
    profileImg: "Manan.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/manan-jethwani",
    githubProfileUrl: "https://www.github.com/mananjethwani",
    email: "",
  },
  {
    name: "Taara Sinh Aatrey",
    description: "Co-Coordinator (2020-21)",
    profileImg: "Tara.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/aatrey07",
    githubProfileUrl: "https://github.com/Taara-Sinh-Aatrey",
    email: "taarasinh1@gmail.com",
  },
  {
    name: "Himanshu Aggarwal",
    description: "Co-Coordinator (2021-22)",
    profileImg: "Himanshu.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/himanshu0923/",
    githubProfileUrl: "https://www.github.com/HimanShu0923",
    email: "",
  },
  {
    name: "Aksh Bansal",
    description: "Co-Coordinator (2021-22)",
    profileImg: "Aksh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/aksh-bansal-0a1073200/",
    githubProfileUrl: "https://github.com/Aksh-Bansal-dev",
    email: "",
  },
  {
    name: "Priyansh Mehta",
    description: "Co-Coordinator (2022-23)",
    profileImg: "PriyanshMehta.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/priyansh61",
    githubProfileUrl: "https://github.com/Priyansh61",
    email: "",
  },
  {
    name: "Shashwat Gupta",
    description: "Coordinator (2022-23)",
    profileImg: "shashwat.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/masterchief164",
    githubProfileUrl: "https://www.github.com/masterchief164",
    email: "shaswat2001.sg@gmail.com",
  },
];
