export const alumniList = [
  {
    name: "Saurabh Joshi",
    description: "Ex-Coordinator(2016-17)",
    profileImg: "Saurabh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/apptica",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Anuraag Singh",
    description: "Ex-Co-Coordinator(2018-19)",
    profileImg: "Anuraag.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/anuraag-singh-231661113",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Shivansh Dhiman",
    description: "Ex-Co-Coordinator(2018-19)",
    profileImg: "Shivansh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/shivansh-dhiman",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Anshuman Sharma",
    description: "Ex-Co-Coordinator(2018-19)",
    profileImg: "Anshuman.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/-anshuman-sharma-",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Arpan Tarkas",
    description: "Ex-Coordinator(2018-19)",
    profileImg: "Arpan.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/arpantarkas",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Pranav Khiste",
    description: "Ex-Co-Coordinator(2019-20)",
    profileImg: "Pranav.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/pranav-khiste-2a38a116a",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Shrey Goel",
    description: "Ex-Co-Coordinator(2019-20)",
    profileImg: "Shrey.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/shrey-goel-21492194",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Ajwad Shaikh",
    description: "Ex-Coordinator(2019-20)",
    profileImg: "Ajwad.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/ajwad-shaikh",
    githubProfileUrl: "https://www.github.com/ajwad-shaikh",
    email: "",
  },
  {
    name: "Manan Jethwani",
    description: "Ex-Co-Coordinator(2020-22)",
    profileImg: "Manan.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/manan-jethwani",
    githubProfileUrl: "https://www.github.com/mananjethwani",
    email: "",
  },
  {
    name: "Tara Sinh Aatrey",
    description: "Ex-Co-Coordinator(2020-22)",
    profileImg: "Tara.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/aatrey07",
    githubProfileUrl: "https://github.com/Taara-Sinh-Aatrey",
    email: "taarasinh1@gmail.com",
  },
  {
    name: "Priyansh Garg",
    description: "Ex-Coordinator(2020-22)",
    profileImg: "priyansh.jpeg",
    linkedInProfileUrl: "https://www.linkedin.com/in/priyansh3133/",
    githubProfileUrl: "",
    email: "",
  },
  {
    name: "Shashwat Gupta",
    description: "Ex-Coordinator(2022-23)",
    profileImg: "shashwat.jpg",
    linkedInProfileUrl: "https://www.linkedin.com/in/masterchief164",
    githubProfileUrl: "https://www.github.com/masterchief164",
    email: "shaswat2001.sg@gmail.com",
  },
];
